/**
 * @fileoverview Static ISO 3166-1 country table — alpha-3 and alpha-2 codes,
 * the ISO English short name, and common informal English aliases. Sourced
 * from the ISO 3166-1 standard; aliases hand-curated for the names agents and
 * users actually type ("USA", "South Korea", "Ivory Coast") that differ from
 * the ISO short form. Consumed by `resolveCountryName` to turn free-form
 * country names into the alpha-3 codes BrAPI `/locations` filters expect.
 *
 * @module services/iso-country/iso-3166-data
 */

import type { IsoCountry } from './types.js';

/** Every ISO 3166-1 officially-assigned country, sorted by alpha-3 code. */
export const ISO_3166_1_COUNTRIES: readonly IsoCountry[] = [
  { alpha3: 'ABW', alpha2: 'AW', name: 'Aruba', aliases: [] },
  { alpha3: 'AFG', alpha2: 'AF', name: 'Afghanistan', aliases: [] },
  { alpha3: 'AGO', alpha2: 'AO', name: 'Angola', aliases: [] },
  { alpha3: 'AIA', alpha2: 'AI', name: 'Anguilla', aliases: [] },
  { alpha3: 'ALA', alpha2: 'AX', name: 'Åland Islands', aliases: [] },
  { alpha3: 'ALB', alpha2: 'AL', name: 'Albania', aliases: [] },
  { alpha3: 'AND', alpha2: 'AD', name: 'Andorra', aliases: [] },
  {
    alpha3: 'ARE',
    alpha2: 'AE',
    name: 'United Arab Emirates',
    aliases: ['UAE'],
  },
  { alpha3: 'ARG', alpha2: 'AR', name: 'Argentina', aliases: [] },
  { alpha3: 'ARM', alpha2: 'AM', name: 'Armenia', aliases: [] },
  { alpha3: 'ASM', alpha2: 'AS', name: 'American Samoa', aliases: [] },
  { alpha3: 'ATA', alpha2: 'AQ', name: 'Antarctica', aliases: [] },
  { alpha3: 'ATF', alpha2: 'TF', name: 'French Southern Territories', aliases: [] },
  { alpha3: 'ATG', alpha2: 'AG', name: 'Antigua and Barbuda', aliases: [] },
  { alpha3: 'AUS', alpha2: 'AU', name: 'Australia', aliases: [] },
  { alpha3: 'AUT', alpha2: 'AT', name: 'Austria', aliases: [] },
  { alpha3: 'AZE', alpha2: 'AZ', name: 'Azerbaijan', aliases: [] },
  { alpha3: 'BDI', alpha2: 'BI', name: 'Burundi', aliases: [] },
  { alpha3: 'BEL', alpha2: 'BE', name: 'Belgium', aliases: [] },
  { alpha3: 'BEN', alpha2: 'BJ', name: 'Benin', aliases: [] },
  { alpha3: 'BES', alpha2: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', aliases: ['Bonaire'] },
  { alpha3: 'BFA', alpha2: 'BF', name: 'Burkina Faso', aliases: [] },
  { alpha3: 'BGD', alpha2: 'BD', name: 'Bangladesh', aliases: [] },
  { alpha3: 'BGR', alpha2: 'BG', name: 'Bulgaria', aliases: [] },
  { alpha3: 'BHR', alpha2: 'BH', name: 'Bahrain', aliases: [] },
  { alpha3: 'BHS', alpha2: 'BS', name: 'Bahamas', aliases: [] },
  { alpha3: 'BIH', alpha2: 'BA', name: 'Bosnia and Herzegovina', aliases: [] },
  { alpha3: 'BLM', alpha2: 'BL', name: 'Saint Barthélemy', aliases: [] },
  { alpha3: 'BLR', alpha2: 'BY', name: 'Belarus', aliases: [] },
  { alpha3: 'BLZ', alpha2: 'BZ', name: 'Belize', aliases: [] },
  { alpha3: 'BMU', alpha2: 'BM', name: 'Bermuda', aliases: [] },
  { alpha3: 'BOL', alpha2: 'BO', name: 'Bolivia, Plurinational State of', aliases: ['Bolivia'] },
  { alpha3: 'BRA', alpha2: 'BR', name: 'Brazil', aliases: [] },
  { alpha3: 'BRB', alpha2: 'BB', name: 'Barbados', aliases: [] },
  { alpha3: 'BRN', alpha2: 'BN', name: 'Brunei Darussalam', aliases: ['Brunei'] },
  { alpha3: 'BTN', alpha2: 'BT', name: 'Bhutan', aliases: [] },
  { alpha3: 'BVT', alpha2: 'BV', name: 'Bouvet Island', aliases: [] },
  { alpha3: 'BWA', alpha2: 'BW', name: 'Botswana', aliases: [] },
  { alpha3: 'CAF', alpha2: 'CF', name: 'Central African Republic', aliases: [] },
  { alpha3: 'CAN', alpha2: 'CA', name: 'Canada', aliases: [] },
  { alpha3: 'CCK', alpha2: 'CC', name: 'Cocos (Keeling) Islands', aliases: [] },
  { alpha3: 'CHE', alpha2: 'CH', name: 'Switzerland', aliases: [] },
  { alpha3: 'CHL', alpha2: 'CL', name: 'Chile', aliases: [] },
  { alpha3: 'CHN', alpha2: 'CN', name: 'China', aliases: [] },
  { alpha3: 'CIV', alpha2: 'CI', name: "Côte d'Ivoire", aliases: ['Ivory Coast'] },
  { alpha3: 'CMR', alpha2: 'CM', name: 'Cameroon', aliases: [] },
  {
    alpha3: 'COD',
    alpha2: 'CD',
    name: 'Congo, Democratic Republic of the',
    aliases: ['Democratic Republic of the Congo', 'DR Congo', 'DRC', 'Congo-Kinshasa', 'Zaire'],
  },
  {
    alpha3: 'COG',
    alpha2: 'CG',
    name: 'Congo',
    aliases: ['Republic of the Congo', 'Congo-Brazzaville'],
  },
  { alpha3: 'COK', alpha2: 'CK', name: 'Cook Islands', aliases: [] },
  { alpha3: 'COL', alpha2: 'CO', name: 'Colombia', aliases: [] },
  { alpha3: 'COM', alpha2: 'KM', name: 'Comoros', aliases: [] },
  { alpha3: 'CPV', alpha2: 'CV', name: 'Cabo Verde', aliases: ['Cape Verde'] },
  { alpha3: 'CRI', alpha2: 'CR', name: 'Costa Rica', aliases: [] },
  { alpha3: 'CUB', alpha2: 'CU', name: 'Cuba', aliases: [] },
  { alpha3: 'CUW', alpha2: 'CW', name: 'Curaçao', aliases: [] },
  { alpha3: 'CXR', alpha2: 'CX', name: 'Christmas Island', aliases: [] },
  { alpha3: 'CYM', alpha2: 'KY', name: 'Cayman Islands', aliases: [] },
  { alpha3: 'CYP', alpha2: 'CY', name: 'Cyprus', aliases: [] },
  { alpha3: 'CZE', alpha2: 'CZ', name: 'Czechia', aliases: ['Czech Republic'] },
  { alpha3: 'DEU', alpha2: 'DE', name: 'Germany', aliases: [] },
  { alpha3: 'DJI', alpha2: 'DJ', name: 'Djibouti', aliases: [] },
  { alpha3: 'DMA', alpha2: 'DM', name: 'Dominica', aliases: [] },
  { alpha3: 'DNK', alpha2: 'DK', name: 'Denmark', aliases: [] },
  { alpha3: 'DOM', alpha2: 'DO', name: 'Dominican Republic', aliases: [] },
  { alpha3: 'DZA', alpha2: 'DZ', name: 'Algeria', aliases: [] },
  { alpha3: 'ECU', alpha2: 'EC', name: 'Ecuador', aliases: [] },
  { alpha3: 'EGY', alpha2: 'EG', name: 'Egypt', aliases: [] },
  { alpha3: 'ERI', alpha2: 'ER', name: 'Eritrea', aliases: [] },
  { alpha3: 'ESH', alpha2: 'EH', name: 'Western Sahara', aliases: [] },
  { alpha3: 'ESP', alpha2: 'ES', name: 'Spain', aliases: [] },
  { alpha3: 'EST', alpha2: 'EE', name: 'Estonia', aliases: [] },
  { alpha3: 'ETH', alpha2: 'ET', name: 'Ethiopia', aliases: [] },
  { alpha3: 'FIN', alpha2: 'FI', name: 'Finland', aliases: [] },
  { alpha3: 'FJI', alpha2: 'FJ', name: 'Fiji', aliases: [] },
  {
    alpha3: 'FLK',
    alpha2: 'FK',
    name: 'Falkland Islands (Malvinas)',
    aliases: ['Falkland Islands'],
  },
  { alpha3: 'FRA', alpha2: 'FR', name: 'France', aliases: [] },
  { alpha3: 'FRO', alpha2: 'FO', name: 'Faroe Islands', aliases: [] },
  { alpha3: 'FSM', alpha2: 'FM', name: 'Micronesia, Federated States of', aliases: ['Micronesia'] },
  { alpha3: 'GAB', alpha2: 'GA', name: 'Gabon', aliases: [] },
  {
    alpha3: 'GBR',
    alpha2: 'GB',
    name: 'United Kingdom of Great Britain and Northern Ireland',
    aliases: ['United Kingdom', 'UK', 'Great Britain', 'Britain', 'England'],
  },
  { alpha3: 'GEO', alpha2: 'GE', name: 'Georgia', aliases: [] },
  { alpha3: 'GGY', alpha2: 'GG', name: 'Guernsey', aliases: [] },
  { alpha3: 'GHA', alpha2: 'GH', name: 'Ghana', aliases: [] },
  { alpha3: 'GIB', alpha2: 'GI', name: 'Gibraltar', aliases: [] },
  { alpha3: 'GIN', alpha2: 'GN', name: 'Guinea', aliases: [] },
  { alpha3: 'GLP', alpha2: 'GP', name: 'Guadeloupe', aliases: [] },
  { alpha3: 'GMB', alpha2: 'GM', name: 'Gambia', aliases: [] },
  { alpha3: 'GNB', alpha2: 'GW', name: 'Guinea-Bissau', aliases: [] },
  { alpha3: 'GNQ', alpha2: 'GQ', name: 'Equatorial Guinea', aliases: [] },
  { alpha3: 'GRC', alpha2: 'GR', name: 'Greece', aliases: [] },
  { alpha3: 'GRD', alpha2: 'GD', name: 'Grenada', aliases: [] },
  { alpha3: 'GRL', alpha2: 'GL', name: 'Greenland', aliases: [] },
  { alpha3: 'GTM', alpha2: 'GT', name: 'Guatemala', aliases: [] },
  { alpha3: 'GUF', alpha2: 'GF', name: 'French Guiana', aliases: [] },
  { alpha3: 'GUM', alpha2: 'GU', name: 'Guam', aliases: [] },
  { alpha3: 'GUY', alpha2: 'GY', name: 'Guyana', aliases: [] },
  { alpha3: 'HKG', alpha2: 'HK', name: 'Hong Kong', aliases: [] },
  { alpha3: 'HMD', alpha2: 'HM', name: 'Heard Island and McDonald Islands', aliases: [] },
  { alpha3: 'HND', alpha2: 'HN', name: 'Honduras', aliases: [] },
  { alpha3: 'HRV', alpha2: 'HR', name: 'Croatia', aliases: [] },
  { alpha3: 'HTI', alpha2: 'HT', name: 'Haiti', aliases: [] },
  { alpha3: 'HUN', alpha2: 'HU', name: 'Hungary', aliases: [] },
  { alpha3: 'IDN', alpha2: 'ID', name: 'Indonesia', aliases: [] },
  { alpha3: 'IMN', alpha2: 'IM', name: 'Isle of Man', aliases: [] },
  { alpha3: 'IND', alpha2: 'IN', name: 'India', aliases: [] },
  { alpha3: 'IOT', alpha2: 'IO', name: 'British Indian Ocean Territory', aliases: [] },
  { alpha3: 'IRL', alpha2: 'IE', name: 'Ireland', aliases: [] },
  { alpha3: 'IRN', alpha2: 'IR', name: 'Iran, Islamic Republic of', aliases: ['Iran'] },
  { alpha3: 'IRQ', alpha2: 'IQ', name: 'Iraq', aliases: [] },
  { alpha3: 'ISL', alpha2: 'IS', name: 'Iceland', aliases: [] },
  { alpha3: 'ISR', alpha2: 'IL', name: 'Israel', aliases: [] },
  { alpha3: 'ITA', alpha2: 'IT', name: 'Italy', aliases: [] },
  { alpha3: 'JAM', alpha2: 'JM', name: 'Jamaica', aliases: [] },
  { alpha3: 'JEY', alpha2: 'JE', name: 'Jersey', aliases: [] },
  { alpha3: 'JOR', alpha2: 'JO', name: 'Jordan', aliases: [] },
  { alpha3: 'JPN', alpha2: 'JP', name: 'Japan', aliases: [] },
  { alpha3: 'KAZ', alpha2: 'KZ', name: 'Kazakhstan', aliases: [] },
  { alpha3: 'KEN', alpha2: 'KE', name: 'Kenya', aliases: [] },
  { alpha3: 'KGZ', alpha2: 'KG', name: 'Kyrgyzstan', aliases: [] },
  { alpha3: 'KHM', alpha2: 'KH', name: 'Cambodia', aliases: [] },
  { alpha3: 'KIR', alpha2: 'KI', name: 'Kiribati', aliases: [] },
  { alpha3: 'KNA', alpha2: 'KN', name: 'Saint Kitts and Nevis', aliases: [] },
  {
    alpha3: 'KOR',
    alpha2: 'KR',
    name: 'Korea, Republic of',
    aliases: ['South Korea', 'Republic of Korea', 'Korea'],
  },
  { alpha3: 'KWT', alpha2: 'KW', name: 'Kuwait', aliases: [] },
  { alpha3: 'LAO', alpha2: 'LA', name: "Lao People's Democratic Republic", aliases: ['Laos'] },
  { alpha3: 'LBN', alpha2: 'LB', name: 'Lebanon', aliases: [] },
  { alpha3: 'LBR', alpha2: 'LR', name: 'Liberia', aliases: [] },
  { alpha3: 'LBY', alpha2: 'LY', name: 'Libya', aliases: [] },
  { alpha3: 'LCA', alpha2: 'LC', name: 'Saint Lucia', aliases: [] },
  { alpha3: 'LIE', alpha2: 'LI', name: 'Liechtenstein', aliases: [] },
  { alpha3: 'LKA', alpha2: 'LK', name: 'Sri Lanka', aliases: [] },
  { alpha3: 'LSO', alpha2: 'LS', name: 'Lesotho', aliases: [] },
  { alpha3: 'LTU', alpha2: 'LT', name: 'Lithuania', aliases: [] },
  { alpha3: 'LUX', alpha2: 'LU', name: 'Luxembourg', aliases: [] },
  { alpha3: 'LVA', alpha2: 'LV', name: 'Latvia', aliases: [] },
  { alpha3: 'MAC', alpha2: 'MO', name: 'Macao', aliases: [] },
  { alpha3: 'MAF', alpha2: 'MF', name: 'Saint Martin (French part)', aliases: [] },
  { alpha3: 'MAR', alpha2: 'MA', name: 'Morocco', aliases: [] },
  { alpha3: 'MCO', alpha2: 'MC', name: 'Monaco', aliases: [] },
  { alpha3: 'MDA', alpha2: 'MD', name: 'Moldova, Republic of', aliases: ['Moldova'] },
  { alpha3: 'MDG', alpha2: 'MG', name: 'Madagascar', aliases: [] },
  { alpha3: 'MDV', alpha2: 'MV', name: 'Maldives', aliases: [] },
  { alpha3: 'MEX', alpha2: 'MX', name: 'Mexico', aliases: [] },
  { alpha3: 'MHL', alpha2: 'MH', name: 'Marshall Islands', aliases: [] },
  { alpha3: 'MKD', alpha2: 'MK', name: 'North Macedonia', aliases: ['Macedonia'] },
  { alpha3: 'MLI', alpha2: 'ML', name: 'Mali', aliases: [] },
  { alpha3: 'MLT', alpha2: 'MT', name: 'Malta', aliases: [] },
  { alpha3: 'MMR', alpha2: 'MM', name: 'Myanmar', aliases: ['Burma'] },
  { alpha3: 'MNE', alpha2: 'ME', name: 'Montenegro', aliases: [] },
  { alpha3: 'MNG', alpha2: 'MN', name: 'Mongolia', aliases: [] },
  { alpha3: 'MNP', alpha2: 'MP', name: 'Northern Mariana Islands', aliases: [] },
  { alpha3: 'MOZ', alpha2: 'MZ', name: 'Mozambique', aliases: [] },
  { alpha3: 'MRT', alpha2: 'MR', name: 'Mauritania', aliases: [] },
  { alpha3: 'MSR', alpha2: 'MS', name: 'Montserrat', aliases: [] },
  { alpha3: 'MTQ', alpha2: 'MQ', name: 'Martinique', aliases: [] },
  { alpha3: 'MUS', alpha2: 'MU', name: 'Mauritius', aliases: [] },
  { alpha3: 'MWI', alpha2: 'MW', name: 'Malawi', aliases: [] },
  { alpha3: 'MYS', alpha2: 'MY', name: 'Malaysia', aliases: [] },
  { alpha3: 'MYT', alpha2: 'YT', name: 'Mayotte', aliases: [] },
  { alpha3: 'NAM', alpha2: 'NA', name: 'Namibia', aliases: [] },
  { alpha3: 'NCL', alpha2: 'NC', name: 'New Caledonia', aliases: [] },
  { alpha3: 'NER', alpha2: 'NE', name: 'Niger', aliases: [] },
  { alpha3: 'NFK', alpha2: 'NF', name: 'Norfolk Island', aliases: [] },
  { alpha3: 'NGA', alpha2: 'NG', name: 'Nigeria', aliases: [] },
  { alpha3: 'NIC', alpha2: 'NI', name: 'Nicaragua', aliases: [] },
  { alpha3: 'NIU', alpha2: 'NU', name: 'Niue', aliases: [] },
  {
    alpha3: 'NLD',
    alpha2: 'NL',
    name: 'Netherlands, Kingdom of the',
    aliases: ['Netherlands', 'Holland'],
  },
  { alpha3: 'NOR', alpha2: 'NO', name: 'Norway', aliases: [] },
  { alpha3: 'NPL', alpha2: 'NP', name: 'Nepal', aliases: [] },
  { alpha3: 'NRU', alpha2: 'NR', name: 'Nauru', aliases: [] },
  { alpha3: 'NZL', alpha2: 'NZ', name: 'New Zealand', aliases: [] },
  { alpha3: 'OMN', alpha2: 'OM', name: 'Oman', aliases: [] },
  { alpha3: 'PAK', alpha2: 'PK', name: 'Pakistan', aliases: [] },
  { alpha3: 'PAN', alpha2: 'PA', name: 'Panama', aliases: [] },
  { alpha3: 'PCN', alpha2: 'PN', name: 'Pitcairn', aliases: [] },
  { alpha3: 'PER', alpha2: 'PE', name: 'Peru', aliases: [] },
  { alpha3: 'PHL', alpha2: 'PH', name: 'Philippines', aliases: [] },
  { alpha3: 'PLW', alpha2: 'PW', name: 'Palau', aliases: [] },
  { alpha3: 'PNG', alpha2: 'PG', name: 'Papua New Guinea', aliases: [] },
  { alpha3: 'POL', alpha2: 'PL', name: 'Poland', aliases: [] },
  { alpha3: 'PRI', alpha2: 'PR', name: 'Puerto Rico', aliases: [] },
  {
    alpha3: 'PRK',
    alpha2: 'KP',
    name: "Korea, Democratic People's Republic of",
    aliases: ['North Korea', 'DPRK'],
  },
  { alpha3: 'PRT', alpha2: 'PT', name: 'Portugal', aliases: [] },
  { alpha3: 'PRY', alpha2: 'PY', name: 'Paraguay', aliases: [] },
  { alpha3: 'PSE', alpha2: 'PS', name: 'Palestine, State of', aliases: ['Palestine'] },
  { alpha3: 'PYF', alpha2: 'PF', name: 'French Polynesia', aliases: [] },
  { alpha3: 'QAT', alpha2: 'QA', name: 'Qatar', aliases: [] },
  { alpha3: 'REU', alpha2: 'RE', name: 'Réunion', aliases: [] },
  { alpha3: 'ROU', alpha2: 'RO', name: 'Romania', aliases: [] },
  { alpha3: 'RUS', alpha2: 'RU', name: 'Russian Federation', aliases: ['Russia'] },
  { alpha3: 'RWA', alpha2: 'RW', name: 'Rwanda', aliases: [] },
  { alpha3: 'SAU', alpha2: 'SA', name: 'Saudi Arabia', aliases: [] },
  { alpha3: 'SDN', alpha2: 'SD', name: 'Sudan', aliases: [] },
  { alpha3: 'SEN', alpha2: 'SN', name: 'Senegal', aliases: [] },
  { alpha3: 'SGP', alpha2: 'SG', name: 'Singapore', aliases: [] },
  {
    alpha3: 'SGS',
    alpha2: 'GS',
    name: 'South Georgia and the South Sandwich Islands',
    aliases: [],
  },
  {
    alpha3: 'SHN',
    alpha2: 'SH',
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    aliases: [],
  },
  { alpha3: 'SJM', alpha2: 'SJ', name: 'Svalbard and Jan Mayen', aliases: [] },
  { alpha3: 'SLB', alpha2: 'SB', name: 'Solomon Islands', aliases: [] },
  { alpha3: 'SLE', alpha2: 'SL', name: 'Sierra Leone', aliases: [] },
  { alpha3: 'SLV', alpha2: 'SV', name: 'El Salvador', aliases: [] },
  { alpha3: 'SMR', alpha2: 'SM', name: 'San Marino', aliases: [] },
  { alpha3: 'SOM', alpha2: 'SO', name: 'Somalia', aliases: [] },
  { alpha3: 'SPM', alpha2: 'PM', name: 'Saint Pierre and Miquelon', aliases: [] },
  { alpha3: 'SRB', alpha2: 'RS', name: 'Serbia', aliases: [] },
  { alpha3: 'SSD', alpha2: 'SS', name: 'South Sudan', aliases: [] },
  { alpha3: 'STP', alpha2: 'ST', name: 'Sao Tome and Principe', aliases: [] },
  { alpha3: 'SUR', alpha2: 'SR', name: 'Suriname', aliases: [] },
  { alpha3: 'SVK', alpha2: 'SK', name: 'Slovakia', aliases: [] },
  { alpha3: 'SVN', alpha2: 'SI', name: 'Slovenia', aliases: [] },
  { alpha3: 'SWE', alpha2: 'SE', name: 'Sweden', aliases: [] },
  { alpha3: 'SWZ', alpha2: 'SZ', name: 'Eswatini', aliases: ['Swaziland'] },
  { alpha3: 'SXM', alpha2: 'SX', name: 'Sint Maarten (Dutch part)', aliases: [] },
  { alpha3: 'SYC', alpha2: 'SC', name: 'Seychelles', aliases: [] },
  { alpha3: 'SYR', alpha2: 'SY', name: 'Syrian Arab Republic', aliases: ['Syria'] },
  { alpha3: 'TCA', alpha2: 'TC', name: 'Turks and Caicos Islands', aliases: [] },
  { alpha3: 'TCD', alpha2: 'TD', name: 'Chad', aliases: [] },
  { alpha3: 'TGO', alpha2: 'TG', name: 'Togo', aliases: [] },
  { alpha3: 'THA', alpha2: 'TH', name: 'Thailand', aliases: [] },
  { alpha3: 'TJK', alpha2: 'TJ', name: 'Tajikistan', aliases: [] },
  { alpha3: 'TKL', alpha2: 'TK', name: 'Tokelau', aliases: [] },
  { alpha3: 'TKM', alpha2: 'TM', name: 'Turkmenistan', aliases: [] },
  { alpha3: 'TLS', alpha2: 'TL', name: 'Timor-Leste', aliases: ['East Timor'] },
  { alpha3: 'TON', alpha2: 'TO', name: 'Tonga', aliases: [] },
  { alpha3: 'TTO', alpha2: 'TT', name: 'Trinidad and Tobago', aliases: [] },
  { alpha3: 'TUN', alpha2: 'TN', name: 'Tunisia', aliases: [] },
  { alpha3: 'TUR', alpha2: 'TR', name: 'Türkiye', aliases: ['Turkey'] },
  { alpha3: 'TUV', alpha2: 'TV', name: 'Tuvalu', aliases: [] },
  { alpha3: 'TWN', alpha2: 'TW', name: 'Taiwan, Province of China', aliases: ['Taiwan'] },
  { alpha3: 'TZA', alpha2: 'TZ', name: 'Tanzania, United Republic of', aliases: ['Tanzania'] },
  { alpha3: 'UGA', alpha2: 'UG', name: 'Uganda', aliases: [] },
  { alpha3: 'UKR', alpha2: 'UA', name: 'Ukraine', aliases: [] },
  { alpha3: 'UMI', alpha2: 'UM', name: 'United States Minor Outlying Islands', aliases: [] },
  { alpha3: 'URY', alpha2: 'UY', name: 'Uruguay', aliases: [] },
  {
    alpha3: 'USA',
    alpha2: 'US',
    name: 'United States of America',
    aliases: ['United States', 'USA', 'US', 'America'],
  },
  { alpha3: 'UZB', alpha2: 'UZ', name: 'Uzbekistan', aliases: [] },
  { alpha3: 'VAT', alpha2: 'VA', name: 'Holy See', aliases: ['Vatican', 'Vatican City'] },
  { alpha3: 'VCT', alpha2: 'VC', name: 'Saint Vincent and the Grenadines', aliases: [] },
  {
    alpha3: 'VEN',
    alpha2: 'VE',
    name: 'Venezuela, Bolivarian Republic of',
    aliases: ['Venezuela'],
  },
  {
    alpha3: 'VGB',
    alpha2: 'VG',
    name: 'Virgin Islands (British)',
    aliases: ['British Virgin Islands'],
  },
  { alpha3: 'VIR', alpha2: 'VI', name: 'Virgin Islands (U.S.)', aliases: ['US Virgin Islands'] },
  { alpha3: 'VNM', alpha2: 'VN', name: 'Viet Nam', aliases: ['Vietnam'] },
  { alpha3: 'VUT', alpha2: 'VU', name: 'Vanuatu', aliases: [] },
  { alpha3: 'WLF', alpha2: 'WF', name: 'Wallis and Futuna', aliases: [] },
  { alpha3: 'WSM', alpha2: 'WS', name: 'Samoa', aliases: [] },
  { alpha3: 'YEM', alpha2: 'YE', name: 'Yemen', aliases: [] },
  { alpha3: 'ZAF', alpha2: 'ZA', name: 'South Africa', aliases: [] },
  { alpha3: 'ZMB', alpha2: 'ZM', name: 'Zambia', aliases: [] },
  { alpha3: 'ZWE', alpha2: 'ZW', name: 'Zimbabwe', aliases: [] },
];
